# Generated by Django 4.2.23 on 2025-08-23 13:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_name_en', models.CharField(max_length=100, null=True)),
                ('city_name_hi', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_hi', models.CharField(max_length=255, null=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('pdf_flag', models.BooleanField(default=False)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='culture_pdf')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Culture',
            },
        ),
        migrations.CreateModel(
            name='DisplayMemberGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_name_en', models.CharField(max_length=255, null=True)),
                ('group_name_hi', models.CharField(max_length=255, null=True)),
                ('group_rank', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Display Groups',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('paitrik_address', models.CharField(blank=True, max_length=255, null=True)),
                ('paitrik_address_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Family',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(help_text='year should be between 1980 - 2025', validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2025)])),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('image', models.FileField(blank=True, null=True, upload_to='gallery')),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('full_name_en', models.CharField(max_length=100, null=True)),
                ('full_name_hi', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name_hi', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name_hi', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place_en', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_place_hi', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('marital_status', models.CharField(choices=[('unmarried', 'Unmarried'), ('married', 'Married')], default='unmarried', max_length=10)),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='Height in cm', null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gotra', models.CharField(blank=True, choices=[('agastya', 'Agastya'), ('alambayana', 'Alambayana'), ('angirasa', 'Angirasa'), ('aankiras', 'Aankiras'), ('aarti', 'Aarti'), ('aashwalaayana', 'Aashwalaayana'), ('aastik', 'Aastik'), ('aatreya', 'Aatreya'), ('baneda', 'Baneda'), ('bhrigu', 'Bhrigu'), ('bharadwaja', 'Bharadwaja'), ('bhargava', 'Bhargava'), ('chandratreya', 'Chandratreya'), ('chyavana', 'Chyavana'), ('dave', 'Dave'), ('garga', 'Garga'), ('gautam', 'Gautam'), ('harita', 'Harita'), ('jamadagni', 'Jamadagni'), ('jambu', 'Jambu'), ('joshi', 'Joshi'), ('kaakshivan', 'Kaakshivan'), ('kanva', 'Kanva'), ('kapi', 'Kapi'), ('kashyapa', 'Kashyapa'), ('kaushika', 'Kaushika'), ('kavachh', 'Kavachh'), ('katyayana', 'Katyayana'), ('kaundinya', 'Kaundinya'), ('kavachhas', 'Kavachhas'), ('kauts', 'Kauts'), ('kotsas', 'Kotsas'), ('kutsa', 'Kutsa'), ('mandavya', 'Mandavya'), ('marichi', 'Marichi'), ('moudgalya', 'Moudgalya'), ('mrukandu', 'Mrukandu'), ('paingya', 'Paingya'), ('parashara', 'Parashara'), ('pulaha', 'Pulaha'), ('pulastya', 'Pulastya'), ('pandya', 'Pandya'), ('reva', 'Reva'), ('rishyashringa', 'Rishyashringa'), ('saandilya', 'Saandilya'), ('shaandilya', 'Shaandilya'), ('shakalya', 'Shakalya'), ('samarayan', 'Samarayan'), ('shandilya', 'Shandilya'), ('shatamarshana', 'Shatamarshana'), ('shaunak', 'Shaunak'), ('shukla', 'Shukla'), ('srivatsa', 'Srivatsa'), ('sutapa', 'Sutapa'), ('tiwadi', 'Tiwadi'), ('trivadi', 'Trivadi'), ('vachchhas', 'Vachchhas'), ('vachchhav', 'Vachchhav'), ('vadhoola', 'Vadhoola'), ('Vashishtha', 'Vasishta'), ('vatsat', 'Vatsat'), ('vatsa', 'Vatsa'), ('vatsak', 'Vatsak'), ('vishvamitra', 'Vishvamitra'), ('vyas', 'Vyas'), ('yajnavalkya', 'Yajnavalkya')], max_length=100, null=True)),
                ('current_address', models.CharField(blank=True, max_length=255, null=True)),
                ('current_address_en', models.CharField(blank=True, max_length=255, null=True)),
                ('current_address_hi', models.CharField(blank=True, max_length=255, null=True)),
                ('current_address_pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('qualification_type', models.CharField(blank=True, choices=[('school', 'School'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], max_length=20, null=True)),
                ('occupation_type', models.CharField(choices=[('none', 'None'), ('job', 'Job'), ('business', 'Business'), ('student', 'Student'), ('retired', 'Retired'), ('housewife', 'Housewife')], default='none', max_length=20)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_address_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SamajApp.city')),
            ],
            options={
                'verbose_name_plural': 'Member',
            },
        ),
        migrations.CreateModel(
            name='NewsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(help_text='Dimensions of image should be: 730 × 548 px', upload_to='news_events/')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('news', 'News'), ('event', 'Event')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News & Events',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter',
            },
        ),
        migrations.CreateModel(
            name='SponsorAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='ads/')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('state_name_en', models.CharField(max_length=100, null=True)),
                ('state_name_hi', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Website Suggestions',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=100)),
                ('village_name_en', models.CharField(max_length=100, null=True)),
                ('village_name_hi', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='SamajApp.city')),
            ],
            options={
                'verbose_name_plural': 'Villages',
                'unique_together': {('village_name', 'city')},
            },
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SamajApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Sandesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='sandesh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandesh_receiver', to='SamajApp.member')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sandesh_sender', to='SamajApp.member')),
            ],
            options={
                'verbose_name_plural': 'Sandesh',
            },
        ),
        migrations.CreateModel(
            name='QualificationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('school_name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('school_name_hi', models.CharField(blank=True, max_length=255, null=True)),
                ('college_name', models.CharField(blank=True, max_length=100, null=True)),
                ('college_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('college_name_hi', models.CharField(blank=True, max_length=100, null=True)),
                ('degree_name', models.CharField(blank=True, choices=[('ba', 'B.A. (Bachelor of Arts)'), ('bsc', 'B.Sc. (Bachelor of Science)'), ('bcom', 'B.Com. (Bachelor of Commerce)'), ('bba', 'BBA (Bachelor of Business Administration)'), ('bbm', 'BBM (Bachelor of Business Management)'), ('bca', 'BCA (Bachelor of Computer Applications)'), ('bcis', 'BCIS (Bachelor of Computer Information Systems)'), ('bpharma', 'B.Pharma (Bachelor of Pharmacy)'), ('btech', 'B.Tech (Bachelor of Technology)'), ('be', 'B.E. (Bachelor of Engineering)'), ('bjmc', 'BJMC (Bachelor of Journalism and Mass Communication)'), ('bms', 'BMS (Bachelor of Management Studies)'), ('bds', 'BDS (Bachelor of Dental Surgery)'), ('bhms', 'BHMS (Bachelor of Homeopathic Medicine & Surgery)'), ('barch', 'B.Arch (Bachelor of Architecture)'), ('bpt', 'BPT (Bachelor of Physiotherapy)'), ('llb', 'LLB (Bachelor of Laws)'), ('bped', 'B.P.Ed (Bachelor of Physical Education)'), ('blisc', 'B.Lib.I.Sc (Bachelor of Library & Information Science)'), ('bse', 'BSE (Bachelor of Science in Education)'), ('mbbs', 'MBBS (Bachelor of Medicine & Surgery)'), ('bams', 'BAMS (Bachelor of Ayurvedic Medicine & Surgery)'), ('bvsc', 'BVSc (Bachelor of Veterinary Science)'), ('ca', 'CA (Chartered Accountant)'), ('cs', 'CS (Company Secretary)'), ('cfa', 'CFA (Chartered Financial Analyst)'), ('fca', 'FCA (Fellow Chartered Accountant)'), ('mfc', 'MFC (Master of Finance and Control)'), ('ma', 'M.A. (Master of Arts)'), ('msc', 'M.Sc. (Master of Science)'), ('mcom', 'M.Com. (Master of Commerce)'), ('mba', 'MBA (Master of Business Administration)'), ('mca', 'MCA (Master of Computer Applications)'), ('mtech', 'M.Tech (Master of Technology)'), ('mhrm', 'MHRM (Master of Human Resource Management)'), ('mphil', 'M.Phil. (Master of Philosophy)'), ('me', 'M.E. (Master of Engineering)'), ('ms', 'MS (Master of Science)'), ('med', 'M.Ed (Master of Education)'), ('mpharma', 'M.Pharma (Master of Pharmacy)'), ('msw', 'MSW (Master of Social Work)'), ('llm', 'LLM (Master of Laws)'), ('dlitt', 'D.Litt (Doctor of Literature)'), ('phd', 'Ph.D. (Doctor of Philosophy)'), ('mch', 'M.Ch (Magister Chirurgiae / Master of Surgery)'), ('md', 'MD (Doctor of Medicine)'), ('pediatrician', 'Pediatrician'), ('dm', 'DM (Doctorate of Medicine)'), ('dnb', 'DNB (Diplomate of National Board)'), ('bed', 'B.Ed (Bachelor of Education)'), ('pgdca', 'PGDCA (Post Graduate Diploma in Computer Applications)'), ('iti', 'ITI (Industrial Training Institute)'), ('polytechnic', 'Polytechnic'), ('stenography', 'Stenography'), ('pgdc', 'PGDC (Post Graduate Diploma in Computer)'), ('pgdll', 'PGDLL (Post Graduate Diploma in Labour Laws)'), ('dca', 'DCA (Diploma in Computer Applications)'), ('dll', 'DLL (Diploma in Labour Laws)'), ('dllb', 'DLLB (Diploma in Law)'), ('bstc', 'BSTC (Basic School Teaching Certificate)'), ('stc', 'STC (School Teaching Certificate)'), ('blisc', 'B.Lib.I.Sc (Bachelor of Library & Information Science)'), ('nursery', 'Nursery'), ('uneducated', 'Uneducated'), ('primary', 'Primary Education'), ('secondary', 'Secondary (10th)'), ('ssc', 'SSC (10th Grade)'), ('puc', 'PUC / HSC / 12th Grade'), ('bpt', 'Bachelor of Physiotherapy'), ('other', 'Other')], max_length=100, null=True)),
                ('other_degree_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_detail', to='SamajApp.member')),
            ],
            options={
                'verbose_name_plural': 'Qualification Details',
            },
        ),
        migrations.CreateModel(
            name='OccupationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name_hi', models.CharField(blank=True, max_length=100, null=True)),
                ('company_location', models.CharField(blank=True, max_length=255, null=True)),
                ('company_location_en', models.CharField(blank=True, max_length=255, null=True)),
                ('company_location_hi', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_description_en', models.TextField(blank=True, null=True)),
                ('job_description_hi', models.TextField(blank=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True)),
                ('business_name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('business_name_hi', models.CharField(blank=True, max_length=100, null=True)),
                ('business_location', models.CharField(blank=True, max_length=255, null=True)),
                ('business_location_en', models.CharField(blank=True, max_length=255, null=True)),
                ('business_location_hi', models.CharField(blank=True, max_length=255, null=True)),
                ('business_description', models.TextField(blank=True, null=True)),
                ('business_description_en', models.TextField(blank=True, null=True)),
                ('business_description_hi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupation_detail', to='SamajApp.member')),
            ],
            options={
                'verbose_name_plural': 'Occupation Details',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='current_address_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SamajApp.state'),
        ),
        migrations.AddField(
            model_name='member',
            name='current_address_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SamajApp.village'),
        ),
        migrations.AddField(
            model_name='member',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_family', to='SamajApp.family'),
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family',
            name='family_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_family', to='SamajApp.member'),
        ),
        migrations.AddField(
            model_name='family',
            name='paitrik_address_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SamajApp.city'),
        ),
        migrations.AddField(
            model_name='family',
            name='paitrik_address_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SamajApp.state'),
        ),
        migrations.AddField(
            model_name='family',
            name='paitrik_address_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SamajApp.village'),
        ),
        migrations.CreateModel(
            name='DisplayMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('member_name_en', models.CharField(max_length=255, null=True)),
                ('member_name_hi', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(choices=[('adhyaksh', 'Adhyaksh'), ('upadhyaksh', 'Upadhyaksh'), ('sachiv', 'Sachiv'), ('sanrakshak', 'Sanrakshak'), ('mahila_adhyaksh', 'Mahila Adhyaksh'), ('koshadhyaksh', 'Koshadhyaksh'), ('saha_sachiv', 'Saha Sachiv'), ('salahkaar', 'Salahkaar'), ('aayojan_samiti', 'Aayojan Samiti'), ('karyakari_sadasya', 'Karyakari Sadasya')], max_length=50)),
                ('member_image', models.FileField(blank=True, null=True, upload_to='samaj_display_members')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('location_en', models.CharField(blank=True, max_length=100, null=True)),
                ('location_hi', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('rank', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SamajApp.displaymembergroup')),
            ],
            options={
                'verbose_name_plural': 'Display Members',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='SamajApp.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='SamajApp.newsevent')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SamajApp.member')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='SamajApp.state'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city_name', 'state')},
        ),
    ]
