# Generated by Django 4.2.23 on 2025-08-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0002_sponsorad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorad',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsorad',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
