# Generated by Django 4.2.23 on 2025-08-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0003_alter_sponsorad_message_alter_sponsorad_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='culture_pdf'),
        ),
        migrations.AddField(
            model_name='culture',
            name='pdf_flag',
            field=models.BooleanField(default=False),
        ),
    ]
