# Generated by Django 4.2.23 on 2025-08-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0004_culture_pdf_culture_pdf_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
