# Generated by Django 4.2.23 on 2025-08-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0005_culture_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
