# Generated by Django 4.2.23 on 2025-08-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0007_smslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
