# Generated by Django 4.2.23 on 2025-08-25 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0009_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='user',
        ),
    ]
