# Generated by Django 4.2.23 on 2025-08-25 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0011_degree_alter_qualificationdetail_degree_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ['degree_name'], 'verbose_name': 'Degree', 'verbose_name_plural': 'Degrees'},
        ),
        migrations.RenameField(
            model_name='degree',
            old_name='code',
            new_name='degree_code',
        ),
        migrations.RenameField(
            model_name='degree',
            old_name='name',
            new_name='degree_name',
        ),
    ]
