# Generated by Django 4.2.23 on 2025-08-25 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0012_alter_degree_options_rename_code_degree_degree_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degree',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
