# Generated by Django 4.2.23 on 2025-08-25 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0013_degree_created_at_degree_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualificationdetail',
            name='degree_name',
        ),
        migrations.AddField(
            model_name='qualificationdetail',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SamajApp.degree'),
        ),
    ]
