# Generated by Django 4.2.23 on 2025-08-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0015_qualificationdetail_degree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='degree_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='degree',
            name='degree_name_hi',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
