# Generated by Django 4.2.23 on 2025-08-25 12:15

from django.db import migrations


def migrate_degrees(apps, schema_editor):
    QualificationDetail = apps.get_model("SamajApp", "QualificationDetail")
    Degree = apps.get_model("SamajApp", "Degree")

    for q in QualificationDetail.objects.all():
        if q.degree_name:  # old char field
            try:
                degree_obj = Degree.objects.get(degree_code=q.degree_name)
                q.degree = degree_obj
                q.save(update_fields=["degree"])
            except Degree.DoesNotExist:
                # fallback: leave null or store in other_degree_text
                q.other_degree_text = q.degree_name
                q.save(update_fields=["other_degree_text"])


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0017_auto_20250825_1732'),
    ]

    operations = [
        migrations.RunPython(migrate_degrees),
    ]
