# Generated by Django 4.2.23 on 2025-08-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0018_auto_20250825_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualificationdetail',
            name='degree_name',
        ),
    ]
