# Generated by Django 4.2.23 on 2025-08-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0020_qualificationdetail_degree_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualificationdetail',
            name='degree_name',
        ),
        migrations.AddField(
            model_name='member',
            name='family_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='track_views_flag',
            field=models.BooleanField(default=False),
        ),
    ]
