# Generated by Django 4.2.23 on 2025-08-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0021_remove_qualificationdetail_degree_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='family_views',
        ),
        migrations.AddField(
            model_name='family',
            name='family_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='family',
            name='track_family_views_flag',
            field=models.BooleanField(default=False),
        ),
    ]
