# Generated by Django 4.2.23 on 2025-08-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0022_remove_member_family_views_family_family_views_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='track_views_flag',
            new_name='track_member_views_flag',
        ),
    ]
