# Generated by Django 4.2.23 on 2025-08-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0023_rename_track_views_flag_member_track_member_views_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='qualification_type',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('school', 'School'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], default='none', max_length=20, null=True),
        ),
    ]
