# Generated by Django 4.2.23 on 2025-08-30 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0024_alter_member_qualification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to='SamajApp.member')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_made', to='SamajApp.member')),
            ],
        ),
    ]
