# Generated by Django 4.2.23 on 2025-08-30 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0025_profileview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_views_received', to='SamajApp.family')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_viewer_made', to='SamajApp.member')),
            ],
        ),
    ]
