# Generated by Django 4.2.23 on 2025-08-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0026_familyview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='family_views',
        ),
    ]
