# Generated by Django 4.2.23 on 2025-08-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0027_remove_family_family_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile_views',
        ),
    ]
