# Generated by Django 4.2.23 on 2025-09-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0028_remove_member_profile_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_code',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
