# Generated by Django 4.2.23 on 2026-07-17 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0033_clean_village_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_deceased',
            field=models.BooleanField(default=False, verbose_name='Passed Away'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='year',
            field=models.PositiveIntegerField(help_text='year should be between 1980 - 2026', validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2026)]),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_name_en',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_name_hi',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
