# Generated by Django 4.2.23 on 2026-07-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SamajApp', '0034_member_is_deceased'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaymember',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Link to the actual community member profile (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='display_cards', to='SamajApp.member'),
        ),
    ]
